export const LOAD_ADMIN_PRODUCTS_REQUEST = "LOAD_ADMIN_PRODUCTS_REQUEST"
export const LOAD_ADMIN_PRODUCTS_SUCCESS = "LOAD_ADMIN_PRODUCTS_SUCCESS"
export const LOAD_ADMIN_PRODUCTS_FAILED = "LOAD_ADMIN_PRODUCTS_FAILED"

export const VIEW_ADMIN_ORDERS_REQUEST = "VIEW_ADMIN_ORDERS_REQUEST"
export const VIEW_ADMIN_ORDERS_SUCCESS = "VIEW_ADMIN_ORDERS_SUCCESS"
export const VIEW_ADMIN_ORDERS_FAILED = "VIEW_ADMIN_ORDERS_FAILED"