
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'

export const DECREASE_QTY = 'DECREASE_QTY'
export const INCREASE_QTY = 'INCREASE_QTY'

export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'