export const CONFIRM_ORDER_REQUEST = 'CONFIRM_ORDER_REQUEST';
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS';
export const CONFIRM_ORDER_FAIL = 'CONFIRM_ORDER_FAIL';

export const SHIPPING_INFO = 'SHIPPING_INFO';
export const GET_IND_USER_ORDER_SUCCESS = 'GET_IND_USER_ORDER_SUCCESS';
export const GET_IND_USER_ORDER_FAIL = 'GET_IND_USER_ORDER_FAIL';
