export const LOAD_PRO_SUCCESS = 'LOAD_PRO_SUCCESS'
export const LOAD_PRO_REQUEST = 'LOAD_PRO_REQUEST'
export const LOAD_PRO_FAIL = 'LOAD_PRO_FAIL'

export const LOAD_SINGLE_SUCCESS = 'LOAD_SINGLE_SUCCESS'
export const LOAD_SINGLE_REQUEST = 'LOAD_SINGLE_REQUEST'
export const LOAD_SINGLE_FAIL = 'LOAD_SINGLE_FAIL'

export const LOAD_RELATED_SUCCESS = 'LOAD_RELATED_SUCCESS'
export const LOAD_RELATED_REQUEST = 'LOAD_RELATED_REQUEST'
export const LOAD_RELATED_FAIL = 'LOAD_RELATED_FAIL'

export const LOAD_TOP_SUCCESS = 'LOAD_TOP_SUCCESS'
export const LOAD_TOP_REQUEST = 'LOAD_TOP_REQUEST'
export const LOAD_TOP_FAIL = 'LOAD_TOP_FAIL'

export const LOAD_TRENDING_SUCCESS = 'LOAD_TRENDING_SUCCESS'
export const LOAD_TRENDING_REQUEST = 'LOAD_TRENDING_REQUEST'
export const LOAD_TRENDING_FAIL = 'LOAD_TRENDING_FAIL'

export const LOAD_NEW_SUCCESS = 'LOAD_NEW_SUCCESS'
export const LOAD_NEW_REQUEST = 'LOAD_NEW_REQUEST'
export const LOAD_NEW_FAIL = 'LOAD_NEW_FAIL'